@api = http://localhost:3001/tasks

GET {{api}}

###
GET {{api}}/48

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json      

{
    "titulo_tarea": "que tal",
    "descp_tarea": "bueno diuas",
    "fecha_creacion": "2022-03-25",
    "id_usuario": "1",
    "id_creator": "2"

}
###
DELETE {{api}}/12


###
PUT {{api}}/26
content-Type: application/json

{
    "titulo_tarea":"hola buenos dias"
}